//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiParcialito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inscripciones
    {
        public int idInscripcion { get; set; }
        public int cursoID { get; set; }
        public int idUser { get; set; }
    
        public virtual cursos cursos { get; set; }
        public virtual user user { get; set; }
    }
}
